data: change circulation category in mass
rero/rero-ils-tools pull request #2
Opened 2021-06-16 08:16 UTC by BadrAly

A new cli set_circulation_category to allow changing the item
circulation category for as many items with one command.

call_example: poetry run tools.py tools update set_circulation_category --help

Co-Authored-by: Aly Badr aly.badr@rero.ch

2021-06-16 08:44 UTC, iGormilhit approved these changes

2021-06-16 10:20 UTC, rerowep requested changes

2021-06-16 10:20 UTC, rerowep commented on README.md
> +export PYTHONPATH=~/rero-ils-tools
This will  not be correct in a POD.

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/__init__.py
> +from .cli.test import app
Maybe test is not the right name for this file?

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/test.py
Why we need this file?

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/update/circ_category.py
> +        error_file.write('[\n')
There is an ` JsonWriter` class for writing json files.

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/update/circ_category.py
> +        new_circ_category = record.get('new_circulation_category')
Not clear if this is an pid?

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/update/circ_category.py
> +                record.update(record, dbcommit=True, reindex=True)
Committing and reindexing every time will be slow for big changes.

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/update/circ_category.py
> +                ids.append(record.id)
This we need only if we bulk index later.

2021-06-16 10:20 UTC, rerowep commented on rero_ils_tools/cli/update/circ_category.py
> +        if counter % 1000 == 0:
This we need only if `dbcommit` is false.

2021-06-16 11:19 UTC, iGormilhit commented on README.md
> +export PYTHONPATH=~/rero-ils-tools
Maybe the message should precise for which use case it is : is it when one wants to test locally ?

2021-06-16 11:42 UTC, iGormilhit reviewed
Improvement on the README.

2021-06-16 11:42 UTC, iGormilhit commented on README.md
> +
You can check the rendering on https://github.com/BadrAly/rero-ils-tools/tree/baa-item_type_modify

```suggestion
## Usage

### For local machines

1. Clone the repository.
1. Set the environment variables:

    export PYTHONPATH=~/rero-ils-tools
    export PATH=$PATH:~/rero-ils-tools/scripts/
    
### For PODs

    export PYTHONPATH=/invenio/src/rero-ils-tools
    export PATH=$PATH:/invenio/src/rero-ils-tools/scripts/
```

2021-06-16 11:42 UTC, iGormilhit commented on README.md
> +```
```suggestion
### Examples

    poetry run tools.py tools update set_circulation_category --help
```

2021-06-17 09:36 UTC, jma approved these changes
I would be great to have a commit message with the same rules/format than rero-ils.

2021-06-17 09:36 UTC, jma commented on README.md
> +## Usage
nice

2021-06-17 09:36 UTC, jma commented on rero_ils_tools/cli/update/circ_category.py
> +    print('DBCOMMIT', counter)
can be removed

2021-06-17 09:36 UTC, jma commented on rero_ils_tools/cli/update/circ_category.py
> +            print('DBCOMMIT', counter)
can be removed

2021-06-17 09:36 UTC, jma commented on rero_ils_tools/cli/update/circ_category.py
> +    db.session.commit()
You can do this only if some ids are left.

2021-06-17 11:48 UTC, rerowep approved these changes

2021-06-17 13:09 UTC, merged